[project]
name = "cosyvoice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "conformer==0.3.2",
    "deepspeed==0.15.1 ; sys_platform == 'linux'",
    "diffusers==0.29.0",
    "fastapi==0.115.6",
    "fastapi-cli==0.0.4",
    "gdown==5.1.0",
    "gradio==5.4.0",
    "grpcio==1.57.0",
    "grpcio-tools==1.57.0",
    "hydra-core==1.3.2",
    "hyperpyyaml==1.2.3",
    "inflect==7.3.1",
    "librosa==0.10.2",
    "lightning==2.2.4",
    "matplotlib==3.7.5",
    "modelscope==1.20.0",
    "networkx==3.1",
    "numpy==1.26.4",
    "omegaconf==2.3.0",
    "onnx==1.16.0",
    "onnxruntime==1.18.0 ; sys_platform == 'darwin' or sys_platform == 'win32'",
    "onnxruntime-gpu==1.18.0 ; sys_platform == 'linux'",
    "protobuf==4.25",
    "pyarrow==18.1.0",
    "pydantic==2.7.0",
    "pyworld==0.3.4",
    "rich==13.7.1",
    "setuptools<70",
    "soundfile==0.12.1",
    "tensorboard==2.14.0",
    "tensorrt-cu12==10.13.3.9 ; sys_platform == 'linux'",
    "tensorrt-cu12-bindings==10.13.3.9 ; sys_platform == 'linux'",
    "tensorrt-cu12-libs==10.13.3.9 ; sys_platform == 'linux'",
    "torch>=2.6.0",
    "torchaudio>=2.6.0",
    "transformers==4.51.3",
    "uvicorn==0.30.0",
    "wetext==0.0.4",
    "wget==3.2",
    "openai-whisper>=20231117",
    "x-transformers==2.11.24",
    "torchcodec>=0.10.0",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]
torchaudio = [{ index = "pytorch-cu128" }]
